#!/usr/bin/env python

import sys

if len(sys.argv) != 2:
    print('Usage:')
    print('    ./Rovarspraket "<input string>"')
    print('Example:')
    print('    ./Rovarspraket "I\'m speaking Robber\'s language!"')
    sys.exit()

text = sys.argv[1]
out = ''
noprint = 'aeiouAEIOU \'\!.'

for letter in text:
    out += str(letter)
    if letter not in noprint:
        out += 'o'
        out += str(letter)
print(out)
